name: deploy-pwa
on:
  workflow_dispatch:
  push:
    branches: [production]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:pwa
      - uses: actions/configure-pages@v5
        name: Setup Pages
      - uses: actions/upload-pages-artifact@v4
        name: Upload build as Pages artifact
        with:
          path: ./dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
